title: Cure
description: "The emotions that good hunters need to cultivate are love and service more than courage. The sentiments of the hunt then become translated into art."
plugins:
  - jekyll-feed
  - jekyll-paginate
markdown: kramdown
paginate: 20                 # 20 articles par page
paginate_path: "/page:num/"  # /page2, /page3, …

