title: Cure
description: "The emotions that good hunters need to cultivate are love and service more than courage. The sentiments of the hunt then become translated into art."
plugins:
  - jekyll-feed
markdown: kramdown
