title: Cure
description: ""
url: https://curerecs.net
baseurl: ""          # très important : vide pour Netlify (pas "/cure")
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: archive
  permalinks:
    category: /c-:name/
markdown: kramdown
paginate: 20                 # 20 articles par page
paginate_path: "/page:num/"  # /page2, /page3, …
feed:
  excerpt_only: false
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

